Traceback (most recent call last):
  File "/home/an/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/an/.local/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/an/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/an/miniconda3/envs/jupyterbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/an/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/an/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/an/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import mean
import os

import kagglehub

# Download latest version
path = kagglehub.dataset_download("adilshamim8/social-media-addiction-vs-relationships")

print("Path to dataset files:", path)
csv_path = os.path.join(path, "Students Social Media Addiction.csv") 
df4 = pd.read_csv(csv_path)
# df1 = pd.read_csv("Mental Health Dataset1.csv")
# df2 = pd.read_csv("mental_health_diagnosis_treatment_2.csv")
# df3 = pd.read_csv("Mental health Depression disorder Data3.csv")
# df4 = pd.read_csv("Students Social Media Addiction4.csv")

# Algemene stijl
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

plt.figure()
sns.boxplot(
    data=df4,
    x="Affects_Academic_Performance",
    y="Avg_Daily_Usage_Hours",
    palette="coolwarm"
)
plt.title("Dagelijks gebruik vs. invloed op academische prestaties")
plt.xlabel("BeÃ¯nvloedt academische prestaties?")
plt.ylabel("Gemiddelde gebruiksuren")
plt.tight_layout()
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 7[0m
[1;32m      4[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mnumpy[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m mean
[1;32m      5[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mos[39;00m
[0;32m----> 7[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mkagglehub[39;00m
[1;32m      9[0m [38;5;66;03m# Download latest version[39;00m
[1;32m     10[0m path [38;5;241m=[39m kagglehub[38;5;241m.[39mdataset_download([38;5;124m"[39m[38;5;124madilshamim8/social-media-addiction-vs-relationships[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'kagglehub'

